### Register a new user no jwt required
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{ 
  "name": "tom",
  "email": "tom@example.com",
  "password": "tom123"
}

### Login a user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "name": "tom",
  "email": "tom@example.com",
  "password": "tom123"
}

### Get all users
GET http://localhost:3000/api/users
Accept: application/json


### Update user with ID 5 (JWT-protected)
PUT http://localhost:3000/api/users/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJpYXQiOjE3NTIxMjEyNzMsImV4cCI6MTc1MjEyNDg3M30.ZCVA_HsyJSSlpn_N2-ZtebX6rtQ7E_3p2EaZtkWAAhs

{
  "name": "Alice Updated",
  "email": "alicesd2updated@example.com",
  "password": "updatedPassword123"
}


### DELETE user with ID 1
DELETE http://localhost:3000/api/users/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTc1MjA5MjU3MCwiZXhwIjoxNzUyMDk2MTcwfQ.3N6KCfSWX69PTAPiNfc1We0vwFiFFRntS9ELFNgmMJI




### Create a new post (JWT-protected)
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE3NTIxMjE4MjAsImV4cCI6MTc1MjEyNTQyMH0.cgWUyQElUbLgWJbGPGCeXCabL6tJspOG7fKr4E1mP4I

{
  "title": "tom post",
  "content": "hello tom hw are you"
}

### Create a comment on a post (replace postId)
POST http://localhost:3000/api/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE3NTIxMjE4MjAsImV4cCI6MTc1MjEyNTQyMH0.cgWUyQElUbLgWJbGPGCeXCabL6tJspOG7fKr4E1mP4I

{
  "postId": 8,
  "content": " comment on bob you suck! "
}

### show all post
GET http://localhost:3000/api/posts?page=1&pageSize=5&sortBy=createdAt&sortOrder=desc&search=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3NTIxMjE1MzQsImV4cCI6MTc1MjEyNTEzNH0.iPKmFqquJsCIh7Rx1BpYbIWEzpB0_OpWlJmwI8BNBJU


### Create a new comment (JWT-protected)
POST http://localhost:3000/api/comments
Content-Type: application/json
Authorization: Bearer <your_token_here>

{
  "postId": 5,
  "content": "This is a comment on post 5"
}

GET http://localhost:3000/api/comments
Authorization: Bearer <your_token_here>

